import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from '../components/Navbar'; 
import Sidebar from '../components/Sidebar'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-gray-50 text-gray-900  `}>
        
        {/* Navbar (fixed height) */}
        <Navbar />

        {/* Sidebar + Main Content */}
        <div className="flex">
          {/* Sidebar (fixed, 64 width) */}
          <Sidebar />

          {/* Main content */}
          <main className="ml-64 mt-16 p-6 w-full">
            {children}
          </main>
        </div>
        
      </body>
    </html>
  );
}
